# permissions for end users to view kyvernoautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kyvernoautoscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kyverno-autoscaler
    app.kubernetes.io/part-of: kyverno-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: kyvernoautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaler.security.nirmata.io
  resources:
  - kyvernoautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaler.security.nirmata.io
  resources:
  - kyvernoautoscalers/status
  verbs:
  - get
