---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaler.security.nirmata.io
  resources:
  - kyvernoautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.security.nirmata.io
  resources:
  - kyvernoautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaler.security.nirmata.io
  resources:
  - kyvernoautoscalers/status
  verbs:
  - get
  - patch
  - update
